In [2]:
import numpy as np
import math

**Array creation**

In [12]:
# single dimension array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# to print the dimensions of an array
a.ndim

1

In [15]:
#length of each dimension
a.shape

(3,)

In [10]:
# multi dimensional array
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
b.ndim

2

In [14]:
b.shape

(3, 3)

In [17]:
# type of items in the array
print(a.dtype)
print(b.dtype)

int64
int64


In [27]:
#Numpy arrays with 0s and 1s
d = np.zeros([2,3])
print(d)

p = np.ones([2,3])
print(p)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


Generating array with random numbers

In [25]:
np.random.rand(2,3)

array([[0.18585168, 0.14544717, 0.60779577],
       [0.76798846, 0.35284975, 0.10627365]])

Generating array in a sequence
(Starting bound, ending bound, difference between the two)

In [24]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Generating sequence of floats (Starting bound, ending bound, # of numbers)

In [26]:
np.linspace(10,50,15)

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

**Array Operations**