In [1]:
import numpy as np
import math

**Array creation**

In [ ]:
# single dimension array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# to print the dimensions of an array
a.ndim

1

In [ ]:
#length of each dimension
a.shape

(3,)

In [ ]:
# multi dimensional array
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 3)

In [ ]:
# type of items in the array
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
#Numpy arrays with 0s and 1s
d = np.zeros([2,3])
print(d)

p = np.ones([2,3])
print(p)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


Generating array with random numbers

In [ ]:
np.random.rand(2,3)

array([[0.18585168, 0.14544717, 0.60779577],
       [0.76798846, 0.35284975, 0.10627365]])

Generating array in a sequence
(Starting bound, ending bound, difference between the two)

In [ ]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Generating sequence of floats (Starting bound, ending bound, # of numbers)

In [ ]:
np.linspace(10,50,15)

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

**Array Operations**

Arithmetic operators on array apply element wise 

In [2]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [3]:
c = a-b
print(c)

d=a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [4]:
farenheit = np.array([0,-10,-5,-15,0])
celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [5]:
celcius>-20

array([ True, False, False, False,  True])

In [8]:
celcius % 2 == 0  

array([False, False,  True, False, False])

numpy also supports matrix manipulation

In [13]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B) # element wise operation
print(A@B) #matrix level operation (dot product)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [15]:
#upcasting

a1 = np.array([[1,2,3],[4,5,6]])
print(a1.dtype)

a2 = np.array([[7.1, 8.2, 9.1], [10.4, 11.2, 12.3]])
print(a2.dtype)

a3 = a1+a2
print(a3)
print(a3.dtype)

int64
float64
[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [16]:
print(a3.sum())
print(a3.max())
print(a3.min())
print(a3.mean())

79.3
18.3
8.1
13.216666666666667


In [18]:
b = np.arange(1,16,1).reshape(3,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

**Indexing, Slicing and Iterating**

- Indexing

In [21]:
# 1 dimensinal
a = np.array([1,3,5,7])
a[2]

5

In [39]:
# 2 dimensional
a = np.array([[1,2],[3,4],[9,7]])
print(a)
a[1,1] #starts at 0

[[1 2]
 [3 4]
 [9 7]]


4

- Boolean Indexing

In [37]:
print(a>5)

[[False False]
 [False False]
 [ True  True]]


In [38]:
print(a[a>5])

[9 7]


Slicing (creating sub array) (:)

In [41]:
a = np.array([1,3,5,7])
print(a[:3])
print(a[2:3])

[1 3 5]
[5]


In [47]:
b = np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [48]:
print(b[:1])

[[1 2 3]]


In [52]:
print(b[:2,0:1]) #2 rows, 1 column

[[1]
 [3]]


**Trying Numpy with Datasets**

In [ ]:
# wines = np.genfromtxt()